#!/usr/bin/env bash
# Script that displays Best School 10 times
i=0; while [ $i -le 9 ]; do echo "Best School"; ((i++)); done
#!/usr/bin/env bash
# Script that displays Best School 10 times
for i in {0..9}
do
	echo "Best School"
done
export i
